### ISSUE TITLE
Organizational Meeting #3

### ISSUE THREAD

**Issue by ababaian** [hackseq/hackseqRNA#13]
Hello @hackseq/hackseqrna_org,

Let's get an organizational meeting going for this week. I thought I opened this issue last week but must have not clicked submit, so pardon the late notice.

**Meeting is set for Thursday 5pm at BCCRC**

## Tentative Agenda
(Jen can you go through and update tasks?)

### Applications are open!
- [x] [hsRNA webpage](hackseq.com/rna) is online. Applications are live.
- [x] Updated [Team Leader Page](https://www.hackseq.com/team-leads)
- [x] Updated [Participant Page](https://www.hackseq.com/participants)
- [x] Reddit thread live
- [x] Poster sent out to RNA Society Newsletter

#### Mail list email
- [x] Email to hackseq mailling list re: hsRNA
-  Last time the email was sent to 'spam' folder in all my emails. How can we avoid this via mailchimp?
- Encourage team leader applications specifically
- Add section to recruit organizers

### Sponsorships
- [x] Updated [Sponsorship Page](https://www.hackseq.com/be-a-partner)
- [ ] Draft template email for new and returning sponsors
- [ ] Affiliation with a program like IOGS or bioinformatics

### Venue
- [ ] Have an update on the cost of venue
- [ ] Extending room blocks
- [ ] booking more rooms for hackathon

# Minutes

## Applications
- Applications  are now live
-- rolling applications for participants
-- give overall priority for early applications
- First round will close **Feb. 28th**
- Current Count: 9 apps, 0 projects
- Main goal: More project applications [ Aim is 10 ]

## Sponsorship
- Justin + Steven to talk tomorrow more about this
- Ideas
-- 10x genomics
-- uber + lyft
--- possibly getting them to sponsor some coupons/vouchers(?)
---- Jenny to ask around for contacts
-- MLH
-- Local tech companies?
--- virogin
--- ABM
--- Context genomics

### RNA society
- retweeting them
- put this on itinerary for their next meeting
- ask for travel grant
 - 2x 1k for conference + event
- winning team to possibly present work at the computational talk at the conference 

## Mail-list / Poster Promotion
- [ ] Jenny to make a common spreadsheet for tracking where we've contacted
- [x] Create a second full-page poster for advertising hackeq (Alex)

### ideas
  - [x] MedGen
  - [ ] omics groups
  - [ ] ecoscope
  - [ ] stemcell network
  - [ ] science in the city
  - [ ] r ladies
  - [ ] scwist
  - [ ] vanbug
  - [ ] Genome Science centre
  - [x] CRC/GrasPods
  - [ ] BCCHRI (?)
  - [ ] UBC/SFU bioinformatics - Alex
  - [ ] Canada bioinformatics network 
  - [x] Epigenetics Journal Club, UBC

### RNA Research Institutes
  - [x] Boulder Colorado
  - [x] Cambridge Medicine
  - [x] Berlin Mol-Bio Institute
  - [x] RNA Institute  - Lethbridge
  - [ ] UCSC RNA mailing list

# TODO (ASAP)
- [x] Artem to put Jenny in contact with room booking
- [x] Send out recruitment mail to hs mailing list (Alex)
- [x] Prepare draft template + media for email to give to other mailing lists to forwards (Alex/Artem)
- [ ] Read over the hackseq website FAQ / and new info pages to provide notes (everyone)
- [ ] Provide feedback on new sponsorship page ( Justin + David  + Stephen )
- [ ] Update the head-hunting spreadsheet, begin to send out emails ( Emre + Alex )

# TODO (not ASAP)
- [ ] Create a hackseq-organizer repository and copy info from hs18 wiki into here.
- [ ] Begin to population hackseq-organizer repo with relavant information to help others organize a hackathon.

**Comment by emreerhan** [comment]
Reddit thread up!
https://www.reddit.com/r/bioinformatics/comments/euw78w/hackseqrna_an_rnathemed_bioinformatics_hackathon/

**Comment by ababaian** [comment]
@imasianxd + @zsteve can you fill out the poll?

**Comment by bfjia** [comment]
Just did. My bad

**Comment by jenjaelin** [comment]
@ababaian for some reason I'm not getting notifications recently for github :P what tasks would you like me to update?

**Comment by ababaian** [comment]
@jenjaelin Can you go through the open issues, close them out if needed and move all the tasks to do here into one place?

**Comment by ababaian** [comment]
@jenjaelin Not sure what's up with the notifications. I don't use github notifications (I just check the site regularly) so I can't help. You're part of the organization so you should have been tagged in theory.

@hackseq/hackseqrna_org meeting time set for Thursday 5pm.

@itsDagu @zsteve can you confirm if you can make this time? It would be good to get all hands on deck and lay out the plan for the next few months.

**Comment by itsDagu** [comment]
@ababaian Sorry, I don't think I can make this one in person, my classes finish at 5pm on Thursdays. I will try my best to join via Skype if it is available.

**Comment by emreerhan** [comment]
@jenjaelin are you watching the repo? You can check at the top of the page where you see an eyeball icon.

**Comment by emreerhan** [comment]
@ababaian can we get the RNA Society to help advertise via RT's and an email to the mailing list?

**Comment by ababaian** [comment]
@emreerhan Yeah. We need to draft a clean recruiting email draft. Something like attached poster perhaps and then we can BLAST it across all the mailing lists. If you can get a draft ready we can finalize it at the meeting.

We also have the old game-boy poster we can re-use. I always liked that one :)

[hsRNA_poster.pdf](https://github.com/hackseq/hackseqRNA/files/4131448/hsRNA_poster.pdf)

**Comment by ababaian** [comment]
@schutzekatze, I don't have the RNA18 abstract book but I have one from a Canadian meeting RiboWest in 2017. It's on the hackseq google drive under "/Teams/hsRNA_teams/"

Ask Emre how to gain access.

**Comment by bfjia** [comment]
@jenjaelin did you find contacts for uber/lyft?

**Comment by jenjaelin** [comment]
got one for Lyft, but not Uber. Will send :)

**Comment by ababaian** [comment]
@SweetiePi Hows the email coming together? I mentioned yesterday but not sure if we confirmed, how about a second poster design based on a refined "RNA" theme of the gameboy poster previously?

**Comment by alexsweeten** [comment]
@ababaian  It's coming together :). I'll send a draft by tonight, I think Monday morning is the best time to send it out.

**Comment by alexsweeten** [comment]
Sent a test email out to hackseq@gmail.com and it seems to have been sent to our spam folder :(

I'll make some modifications today to try and avoid this.

**Comment by ababaian** [comment]
try making an alternative gmail account, "hackseq.collective" and use that as the sender. If it's new it could possibly avoid spam?

Edit: Can you also add a little bit at the end that we are recruiting organizers too

**Comment by ababaian** [comment]
@SweetiePi last one didn't go to my spam folder :) I think this might be a work-around then.

Did you register the "hackseq-collective@gmail.com" account for real, we should forward mail from there to the main hackseq account? I was in the process of registering "hackseq.collective@gmail.com" but a dash works too : )

**Comment by alexsweeten** [comment]
No I haven't registered it yet. Dash or dot should be fine.

**Comment by ababaian** [comment]
dot is registered : )

I think it will take a little bit of time to set up mail forwarding but it's there.

**Comment by alexsweeten** [comment]
Cool, unless you have any additions to the email I'll send it out!

**Comment by bfjia** [comment]
did we start sending out emails to the participants yet?

**Comment by ababaian** [comment]
The hackseq mailling list email has been sent. What email do you mean @imasianxd?

**Comment by bfjia** [comment]
participant invites to other maillists

**Comment by ababaian** [comment]
I've started sending it out via the Email Flyer to some mailing lists to get the ball rolling yes [See Flyer](https://github.com/hackseq/hackseqRNA/issues/15#issuecomment-582424654)
