### ISSUE TITLE
Org-meet 4

### ISSUE THREAD

**Issue by ababaian** [hackseq/hackseqRNA#16]
Hey @hackseq/hackseqrna_org 

Let's have the next meeting a little bit earlier then usual so we can coordinate the application/sponsorship phase a little bit better. Also we can get everyone to come with more heads up : )

Plan for an extra hour or two afterwards for :beers: 

@hackseq/hackseqrna_org Meeting is Wednesday at 6pm at the BCCRC.

# Agenda
- [x] Affiliations for everyone. Finalize and update github/website.

### LSI
- Tentative booking is available for LSI atrium (+ room 1330 after 12:00pm Friday)
- To confirm, require [security and custodial booking confirmations ](http://facilities-med.sites.olt.ubc.ca/files/2017/09/LSC-Facility-Usage-Guidelines_Sept-2017.pdf). (Volunteer ASAP)
- Artem/Jen asked MedGen to affiliate for discount

### UBC residence
- Booking blocks are in 18 or 24 beds:
- Walter Gage Standard Singles at $60 a night (Private bedroom with single bed in a six-bedroom shared apartment. Guests share a washroom, lounge with flat-panel TV, breakfast bar, and kitchen (not equipped with dishes, cookware, etc.)
- We can have individual bookings (i.e. guests book themselves). Guests must book at least 30 days in advance
 - Individual bookings requires us to put down a 10% deposit. We get the deposit back if 80% of the block (14 beds) are booked.
- **let me know what you guys think on this so I can get back to UBC housing**

## Applications 
First round closes on Feb 28th. Still 9 days. Will likely spike in last two days.

### Numbers
- Participants: 38 applications - Participants
- Team Leads: 0 applications - several inquiries.

### Project Leader Headhunting
- [ ] Update Emre

### Mailing List Reach
Need someone to take charge and systematically complete this. Create shared spreadsheet and systematically reach out to all organizations. [Link to email template](https://github.com/hackseq/hackseqRNA/issues/15#issuecomment-582424654)

More?

** Local **
  - [x] MedGen
  - [ ] Local omics groups
  - [ ] ecoscope
  - [ ] stemcell network
  - [ ] science in the city
  - [ ] r ladies
  - [ ] scwist
  - [ ] vanbug
  - [ ] Genome Science centre
  - [x] CRC/GrasPods
  - [ ] BCCHRI (?)
  - [ ] UBC/SFU bioinformatics - Alex
  - [ ] Canada bioinformatics network 
  - [x] Epigenetics Journal Club, UBC

** Institutes **
  - [x] Boulder Colorado
  - [x] Cambridge Medicine
  - [x] Berlin Mol-Bio Institute
  - [x] RNA Institute  - Lethbridge
  - [ ] UCSC RNA mailing list

** RNA Society **
- [x] RNA Society mail-list (pending?)

## Sponsorship
- [ ] Grant application update (Artem + Justin + Noushin)
- [ ] Sponsors Update (Justin + Casey + Stephen)

# TODO (not ASAP)
- [ ] Reach out to ECOSCOPE about LSI space booking for October hackeq20.
- [ ] Create a hackseq-organizer repository and copy info from hs18 wiki into here. (Volunteeer)
- [ ] Begin compiling pre-hackathon questionnaire for a survey. Take lead on writing draft of the meeting report / hackseq 5 year update report. (Volunteer / Noushin?)

# Minutes

## Sponsorships
- NSF Grant: 50k USD. We would partition it 30k for hackseq organization costs, and 20k towards travel grants for participant applications.
- We have names & signatures from 5 MedGen faculty. 
- Cover cost up front, reimbursed from MIT.

- Sharon from BC Bioinformatics will probably sponsor us again
- AbCellera interested if they give a talk. We'll want to keep it short or move earlier, as the timing was not great during hs19.
- Possible sponsorship from igsn.
- We should bump Shaun Jackman and Michelle Crown for 10x Genomics and Genome BC sponsorships ASAP.
- We should contact Mark hill from StemCell.

## TODO
- Need someone to take care of security/custodian for LSI booking. (Alex)
- UBC residence block booking. Get a quote, put it into NSF grant. (Jen)
- Fork repo to put hackseqRNA into NCBI hackathons. (Emre)
- Create Excel file for mailing lists. (Emre)

### Contact
- Vanbug (Ask Baraa)
- GSC Celine & RocketChat (Alex)
- UBC Math & Stats Depeartment (Stephen)
- R Ladies & Scwist, we should contact Noushin.
- Bioinformatics.ca (Emre)
- Email eligible participants to lead a team (Emre)

**Comment by bfjia** [comment]
I'm going to be away in europe for a conference next week. I will be 9hrs in the future from all of ya. I can update whatever necessary ahead of time.

**Comment by NoushinN** [comment]
I have been missing in action but is there any help I can provide as a remote participant? I am seriously considering participation as well!

**Comment by ababaian** [comment]
Ramping up on Twitter and other social media platforms as always @NoushinN :)

I think @emreerhan could also coordinate finding and emailing different professors/research institutes to reach out to.

**Comment by ababaian** [comment]
Bump, can we all fill out this poll to finalize a room? @emreerhan We added next Wed as well as a possible time, can you update your response? Looks like it's next Wed.
@schutzekatze @zsteve

**Comment by ababaian** [comment]
@hackseq/hackseqrna_org Meeting is Wednesday at 6pm at the BCCRC.

**Comment by alexsweeten** [comment]
I'll be going to The Hive for bouldering after our meeting, if anyone else is interested.

**Comment by ababaian** [comment]
Oooh I'll be down for a bit of climbing

**Comment by jenjaelin** [comment]
something unexpected came up and I have to make a rather rushed trip down
to the states for a few days. I'll post what I have for updates on venue
and lodging bookings if you guys could discuss that it would be great.
Sorry about that and I'm sad to be missing out on climbing post as well.

**Comment by ababaian** [comment]
:'( We'll miss you

**Comment by emreerhan** [comment]
Oops, forgot to respond. I'll be there for the meeting. Cannot join for activities after; I have to be home at 7:30, so I can only stay for an hour.

**Comment by alexsweeten** [comment]
I forgot the Hive has member exclusive hours until 9pm on wednesdays :grimacing: 

Will still go at 9 if you're up for it @ababaian

**Comment by ababaian** [comment]
That's a bit late for the little one. Would you be up for going to cliffhangers?

**Comment by zsteve** [comment]
Hey I'm stuck in traffic bc of pipeline protest, might be late sorry!

**Comment by bfjia** [comment]
Same here....


-------- Original message --------

**Comment by ababaian** [comment]
You're in town Justin? No worries, protesters gatta protest ¯\_(ツ)_/¯

**Comment by jenjaelin** [comment]
@hackseq/hackseqrna_org did you come to a decision on the residences? i.e. should I book a room block?

**Comment by ababaian** [comment]
I think we were a little uncertain why? Can people book the UBC res. independently?

**Comment by ababaian** [comment]
@SweetiePi Can you post the meeting minutes in this thread plz?

**Comment by jenjaelin** [comment]
@ababaian so they can book independently but risk there being no space? booking a block means that the rooms are "reserved" for individuals for hackseqRNA people to book.

But yah if it seems like we won't fill it, I can just tell them we aren't interested.
